(ns telegram-bot-lib.chat-action)

(def typing "typing")
(def upload_photo "upload_photo")
(def record_video "record_video")
(def upload_video "upload_video")
(def record_audio "record_audio")
(def upload_audio "upload_audio")
(def upload_document "upload_document")
(def find_location "find_location")